on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  issue_comment:
  workflow_dispatch:

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ailabcommonacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Run PR Agent container
        run: |
          docker pull ailabcommonacr.azurecr.io/nortal-pr-agent:latest
          docker run --rm \
            -e GITHUB_TOKEN \
            -e OPENAI_KEY \
            -e CONFIG.OTEL_BASIC_AUTH_USERNAME \
            -e CONFIG.OTEL_BASIC_AUTH_PASSWORD \
            -e PR_REVIEWER.EXTRA_INSTRUCTIONS \
            ailabcommonacr.azurecr.io/nortal-pr-agent:latest


