on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  issue_comment:
  workflow_dispatch:

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ailabcommonacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Pull PR Agent image
        run: |
          IMAGE=ailabcommonacr.azurecr.io/nortal-pr-agent:latest
          docker pull "$IMAGE"
      
      - name: Run PR Agent container
        env:
            OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            CONFIG__OTEL_BASIC_AUTH_USERNAME: ${{ vars.OTEL_BASIC_AUTH_USERNAME }}
            CONFIG__OTEL_BASIC_AUTH_PASSWORD: ${{ secrets.OTEL_BASIC_AUTH_PASSWORD }}
            CONFIG__GIT_PROVIDER: "github"
            PR_URL: ${{ github.event.pull_request.html_url }}
            IMAGE: ailabcommonacr.azurecr.io/nortal-pr-agent:latest
        run: |
          set -euo pipefail
          
          docker run --rm -e OPENAI_KEY -e GITHUB_TOKEN -e CONFIG__OTEL_BASIC_AUTH_USERNAME -e CONFIG__OTEL_BASIC_AUTH_PASSWORD -e CONFIG__GIT_PROVIDER \
            "$IMAGE" --pr_url "${PR_URL}" describe

          
          docker run --rm -e OPENAI_KEY -e GITHUB_TOKEN -e CONFIG__OTEL_BASIC_AUTH_USERNAME -e CONFIG__OTEL_BASIC_AUTH_PASSWORD -e CONFIG__GIT_PROVIDER \
            "$IMAGE" --pr_url "${PR_URL}" review

          
          docker run --rm -e OPENAI_KEY -e GITHUB_TOKEN -e CONFIG__OTEL_BASIC_AUTH_USERNAME -e CONFIG__OTEL_BASIC_AUTH_PASSWORD -e CONFIG__GIT_PROVIDER \
            "$IMAGE" --pr_url "${PR_URL}" improve


